language: node_js
node_js:
- 10
cache:
  directories:
  - "$HOME/.npm"
script:
- yarn build
deploy:
  provider: firebase
  project: foreign-field
  only: functions
  edge: true
  token:
    secure: pHWYNBp8dpX/0bjhu0g3/VBV0K/QpZbrEyzjoFcnIyM2pb02QmN54goAhyxa0fAs+H06pW6Jt+EQ9dtAVysLfArIqEfNXndKy3r/dYs2GWjGq2yvo4TfB+HAeqM8VTv+lU8Rl2EFGHEZrPl8rLNmagh7c9Y+zGZFEiojj9p4YTQQSLMZzwnKR5R0XmQvmNwWUvyxKMKButwYUkFG9RdlzGW4GGjmglOW1Fm7zA8jWofxLsT9J7IXC2vZlfuutWDGK+lTTCMWfAdnrChLiygzgREEFAeDONNa2V2pTULkJ3U/H4Ar1TUJkHSU5D0UnzwUcG73FVsSInjKL12PCzrhCv6IoEGxDmmZ2flxZMCfoolAU8UatqdhwT97o9YrLJa4ZVLpjooc8CR1ifq+QQ6QRfJS+pdpWMmz0MipqV6fP6PX/z83G82oicmOEEEst4ybX8tOfzWBnE0nlrk0WgdAWv3fJY5sVBZCL2DpDfPXGT/9Dq7Aly+qGgRDMsyfzxm00O8uovIYESg8TxfpCPdGs1LfsE5KHw0ETztEpXpef0+1jXHWVGCfsccJKYDrxFE7JDRmq1T0vbD7/Ev/fUSQLmgywIgVdvHbytWEGJ2wG9lXTMpedIp1YExnFXFwHj5B7lKlAkQQsadlxOMKkOSwen+xMaksFkqKg/WSqZIXLzQ=
  on:
    branch: master
